# Generated by Django 3.1.3 on 2020-11-19 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20201117_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('86b99ef5-d858-4ace-b1cf-0f10c9b2d6b1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
