# Generated by Django 2.1.7 on 2020-11-22 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20201119_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ec2ac00d-e607-4f50-aeda-3721724816c1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
