# Generated by Django 3.1.3 on 2020-11-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_at',), 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
